// Generate the patchable-symbol list from hncode's own source.
//
// `api.patch('file.js#symbol', handler)` works by name, so the only thing a plugin
// author needs is to know WHICH names exist. This script scans the main package's
// src/*.js and emits both halves of that list:
//
//   targets.js   — a runtime array (PATCH_TARGETS) + a Set, so a plugin can check
//                  a target programmatically.
//   targets.d.ts — a literal union type (PatchTarget) so an editor completes and
//                  type-checks the string.
//
// It is the hncode equivalent of Minecraft's `TargetClass.class`: the concrete
// list of things a mixin may inject into. Source of truth is the main package, so
// re-run this (`npm run gen`) after the main package changes and before publishing.
//
// Usage (from hncode-sdk/):
//   node scripts/gen-targets.mjs [path-to-hncode-root]
//
// Default root is the parent directory (the monorepo layout: hncode-sdk/ sits
// inside the hncode checkout). When this package is published standalone there is
// no src/ to scan, so the generated files are committed and shipped as-is.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const sdkRoot = path.resolve(here, '..');
const hncodeRoot = path.resolve(process.argv[2] || path.join(sdkRoot, '..'));
const srcDir = path.join(hncodeRoot, 'src');

if (!fs.existsSync(srcDir)) {
  console.error(`[gen-targets] no src/ at ${srcDir}`);
  console.error('  pass the hncode checkout root as the first argument, e.g.');
  console.error('  node scripts/gen-targets.mjs /path/to/hncode');
  process.exit(1);
}

// Only these files are reachable by the load hook (see src/patch.js: it rewrites
// modules whose directory is src/). A nested file (src/tools/x.js) is NOT patched
// by a target of "x.js#…" unless the hook were widened, so we do not advertise it.
const files = fs.readdirSync(srcDir).filter((f) => f.endsWith('.js'));

/** @type {{ id: string, file: string, base: string, method: string | null }[]} */
const targets = [];

for (const file of files) {
  const src = fs.readFileSync(path.join(srcDir, file), 'utf8');
  const lines = src.split('\n');

  for (const line of lines) {
    // export function NAME( / export async function NAME(
    let m = /^export\s+(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/.exec(line);
    if (m) { targets.push({ id: `${file}#${m[1]}`, file, base: m[1], method: null }); continue; }
    // export const NAME = … (only function-ish values can be wrapped meaningfully;
    // plain data would be reassigned but calling it makes no sense — still listed,
    // because a plugin may legitimately replace a constant).
    m = /^export\s+(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=/.exec(line);
    if (m) { targets.push({ id: `${file}#${m[1]}`, file, base: m[1], method: null }); continue; }
    // export class NAME
    m = /^export\s+class\s+([A-Za-z_$][\w$]*)/.exec(line);
    if (m) {
      const cls = m[1];
      // Collect the class's own methods (2-space indent, single name, paren).
      const classBody = extractClassBody(src, cls);
      const methods = new Set();
      for (const ln of classBody.split('\n')) {
        const mm = /^\s{2}(?:async\s+)?(?:static\s+)?(?:get\s+|set\s+)?([A-Za-z_$][\w$]*)\s*\(/.exec(ln);
        if (!mm) continue;
        const name = mm[1];
        if (name === 'constructor') continue;
        methods.add(name);
      }
      for (const name of methods) {
        targets.push({ id: `${file}#${cls}.${name}`, file, base: cls, method: name });
      }
    }
  }
}

/** Slice out `export class NAME { … }` by brace counting. */
function extractClassBody(src, cls) {
  const start = src.indexOf(`class ${cls}`);
  if (start < 0) return '';
  const open = src.indexOf('{', start);
  if (open < 0) return '';
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (c === '{') depth++;
    else if (c === '}') { depth--; if (depth === 0) return src.slice(open, i + 1); }
  }
  return src.slice(open);
}

// De-dup (a name may appear in several regex passes) and sort for stable diffs.
const seen = new Set();
const unique = targets.filter((t) => (seen.has(t.id) ? false : (seen.add(t.id), true)));
unique.sort((a, b) => a.id.localeCompare(b.id));

// ---------------------------------------------------------------------------
// targets.js
// ---------------------------------------------------------------------------
const jsLines = [
  '// GENERATED by scripts/gen-targets.mjs — do not edit by hand.',
  '//',
  '// Every symbol in hncode\'s src/ that a plugin may target with',
  '// `api.patch("file.js#symbol", handler)`. Regenerate after the main package',
  '// changes: `npm run gen`.',
  '',
  `export const PATCH_TARGETS = ${JSON.stringify(unique.map((t) => t.id), null, 2)};`,
  '',
  '/** Fast membership test for a target string. */',
  'export const PATCH_TARGET_SET = new Set(PATCH_TARGETS);',
  '',
  '/** True when `target` names a real, patchable symbol. */',
  'export function isPatchTarget(target) { return PATCH_TARGET_SET.has(String(target)); }',
  '',
  `export const GENERATED_FROM = ${JSON.stringify(`hncode src/ (${files.length} files, ${unique.length} symbols)`)};`,
  '',
];
fs.writeFileSync(path.join(sdkRoot, 'targets.js'), jsLines.join('\n'), 'utf8');

// ---------------------------------------------------------------------------
// targets.d.ts
// ---------------------------------------------------------------------------
const tsLines = [
  '// GENERATED by scripts/gen-targets.mjs — do not edit by hand.',
  `// ${unique.length} patchable symbols across ${files.length} files.`,
  '',
  '/** A symbol a plugin may pass to `api.patch(target, handler)`. */',
  'export type PatchTarget =',
  unique.map((t) => `  | ${JSON.stringify(t.id)}`).join('\n') + ';',
  '',
  '/** Every patchable target, at runtime. */',
  'export declare const PATCH_TARGETS: readonly PatchTarget[];',
  'export declare const PATCH_TARGET_SET: Set<string>;',
  'export declare function isPatchTarget(target: string): boolean;',
  'export declare const GENERATED_FROM: string;',
  '',
];
fs.writeFileSync(path.join(sdkRoot, 'targets.d.ts'), tsLines.join('\n'), 'utf8');

console.log(`[gen-targets] ${unique.length} targets from ${files.length} files -> targets.js, targets.d.ts`);
